---
title: "RA_project"
date: "2/24/2021"
output:
  pdf_document: default
  html_document: default
---

```{r}
library(rmarkdown)
library(knitr)
library(haploR)
library(LDlinkR)
library(qqman)
```


The analysis is aimed to retrieve information regarding the provided list of SNPs
```{r}
fileName = "listOfSnps"
con=file(fileName,open="r")
#SNPs <-readLines(con)

SNPs=c("rs2258734")
x <- queryHaploreg(query=SNPs)
if(length(x)!=0) {
subset.high.LD.RA <- x[as.numeric(x$is_query_snp) >0.8, 
                    c("rsID", "r2", "chr", "pos_hg38", "is_query_snp", "ref", "alt")]
  
}
head(subset.high.LD.RA)
```


```{r}
BigTable <- data.frame(matrix(data = NA, ncol = 10))
colnames(BigTable) <- (c("RS_Number","Coord","Alleles","MAF","Distance","Dprime","R2","Correlated_Alleles","RegulomeDB","Function"))
```

```{r}
for (snp in SNPs ){
  
  my_proxies <- LDproxy(snp = snp, 
                        pop = c("EUR","EAS", "SAS"), 
                        r2d = "r2", 
                        token = "6796839e9d86"
                       )
  
  df = my_proxies
  variants_in_highLD <- df[which(df$R2>0.9),]
  list_of_rs <- variants_in_highLD

  BigTable = rbind(BigTable,as.data.frame(list_of_rs))
  
}

BigTable = BigTable[-1,]
head(BigTable)
```

```{r}
my_output <-  LDexpress(SNPs, 
            pop = "CEU", 
            tissue = "ALL", 
            r2d = "r2", 
            #r2d_threshold = 0.8, 
            p_threshold = 0.05, 
            win_size = 500000, 
            token = "6796839e9d86", 
            file = FALSE
           )

head(my_output)
```



```{r}
test <- my_output#head(my_output[which(my_output$Tissue=="Whole Blood"),])
test <- cbind(as.data.frame(test$RS_ID),
              as.numeric(t(
                as.data.frame(
                  strsplit(
                    do.call(
                      rbind, strsplit((test$Position), ":"))[,1],"chr"),
                col.names = F)[2,])),
              as.data.frame(1:nrow(x = test)),
              as.data.frame(as.numeric(test$P_value)))
colnames(test) <- c("SNP","chr","BP", "position")
rownames(test) <- as.list(1:nrow(x = test))


manhattan(test)
```

```{r}
GWASout <- GWASout[order(GWASout$Neg_logP, decreasing = T),]
png(paste(target, ".png", sep = ""), height = 500,width = 1000)
GWAS_Manhattan(GWASout)

```